name: ML-sales-prediction

on:
  push:
    branches: [main]

env:
  IMAGE_NAME: aleem227/sales_prediction
  PROJECT_ID: sales-prediction-vm

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./Dockerfile
          cache-from: none
          push: true
          tags: ${{ env.IMAGE_NAME }}:beta
          labels: ${{ steps.meta.outputs.labels }}
          
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: 'actions/checkout@v4'

    - id: 'auth'
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GCP_KEY }}'

    - id: 'compute-ssh'
      uses: 'google-github-actions/ssh-compute@v1'
      with:
        instance_name: 'prediction-vm'
        zone: 'us-central1-f'
        ssh_private_key: '${{ secrets.GCP_SSH_PRIVATE_KEY }}'
        command: |
                sudo docker pull docker.io/aleem227/sales_prediction:beta
                sudo docker stop sales_prediction || true
                sudo docker rm sales_prediction || true
                sudo docker run -d --name sales_prediction -p 8081:8080 docker.io/aleem227/sales_prediction:beta
