name: ML-sales-prediction

on:
  push:
    branches: [main]

env:
  REGISTRY: docker.io
  IMAGE_NAME: aleem227/sales_prediction
  CI: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./Dockerfile
          cache-from: none
          push: true
          tags: ${{ env.IMAGE_NAME }}:beta
          labels: ${{ steps.meta.outputs.labels }}

      # - name: Upload model.keras
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: model
      #     path: ./
        
      - name: Create Release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.PAT }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "Model"
          files: |
            daily_sales_count_model.h5