name: ML-sales-prediction

on:
  push:
    branches: [main]

env:
  IMAGE_NAME: aleem227/sales_prediction
  PROJECT_ID: prediction-vm

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          version: 'latest'
          service_account_key: ${{ secrets.GCP_KEY }}
          project_id: ${{ env.PROJECT_ID }}
          export_default_credentials: true

      - name: Build Docker Image
        run: docker build -t $IMAGE_NAME:latest .

      - name: Configure Docker Client for GCR
        run: |
          gcloud auth configure-docker --quiet  # Configure Docker to use Google Cloud credentials for GCR

      - name: Configure Docker Client for Artifact Registry
        run: |
          gcloud auth configure-docker us-central1-docker.pkg.dev --quiet  # Configure Docker to use Google Cloud credentials for Artifact Registry in us-central1 region

      - name: Push Docker Image to Container Registry (GCR)
        run: |
          docker tag $IMAGE_NAME:latest gcr.io/$PROJECT_ID/$IMAGE_NAME:latest
          docker push gcr.io/$PROJECT_ID/$IMAGE_NAME:latest

      - name: Push Docker Image to Artifact Registry
        run: |
          docker tag $IMAGE_NAME:latest us-central1-docker.pkg.dev/$PROJECT_ID/images/$IMAGE_NAME:latest
          docker push us-central1-docker.pkg.dev/$PROJECT_ID/images/$IMAGE_NAME:latest

      - name: Deploy to GCP VM
        run: |
          gcloud compute ssh --zone "us-central1-f" "prediction-vm" --command "
            sudo docker pull gcr.io/$PROJECT_ID/$IMAGE_NAME:latest
            sudo docker stop sales_prediction || true
            sudo docker rm sales_prediction || true
            sudo docker run -d --name sales_prediction -p 8081:8080 gcr.io/$PROJECT_ID/$IMAGE_NAME:latest
          "
