name: ML-sales-prediction

on:
  push:
    branches: [main]

env:
  REGISTRY: docker.io
  IMAGE_NAME: aleem227/sales_prediction
  CI: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          cache-from: none
          push: true
          tags: ${{ env.IMAGE_NAME }}:beta
          labels: ${{ steps.meta.outputs.labels }}

      - name: Create Release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.PAT }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "Model"
          files: |
            daily_sales_count_model.h5

      - name: Install Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          version: 'latest'
          service_account_key: ${{ secrets.GCP_KEY }}
          export_default_credentials: true

      - name: Deploy to GCP VM
        run: |
          gcloud auth activate-service-account --key-file <(echo "${{ secrets.GCP_KEY }}")
          gcloud compute ssh --zone "us-central1-f" "prediction-vm" --command "
            sudo docker pull ${{ aleem227/sales_prediction }}:beta
            sudo docker stop sales_prediction || true
            sudo docker rm sales_prediction || true
            sudo docker run -d --name sales_prediction -p 80:80 ${{ aleem227/sales_prediction }}:beta
          "
