name: ML-sales-prediction

on:
  push:
    branches: [main]

env:
  IMAGE_NAME: aleem227/sales_prediction
  PROJECT_ID: sales-prediction-vm

jobs:
  authenticate:
    runs-on: ubuntu-latest
    steps:
    - uses: 'actions/checkout@v4'

    - id: 'auth'
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GCP_KEY }}'

    - id: 'compute-ssh'
      uses: 'google-github-actions/ssh-compute@v1'
      with:
        instance_name: 'prediction-vm'
        zone: 'us-central1-f'
        ssh_private_key: '${{ secrets.GCP_SSH_PRIVATE_KEY }}'
        command: 'touch /testfile'
